BootStrap: docker
From: ubuntu:24.04

%post

    export DEBIAN_FRONTEND=noninteractive

    mkdir /revbayes
    
    echo "Installing required packages..."
    
    # revbayes dependencies
    apt-get update -y
    apt-get install -y build-essential bash-completion git cmake

    # install boost
    apt-get install -y software-properties-common
    add-apt-repository universe
    apt-get update -y
    apt-get install -y libboost-all-dev

    # download revbayes
    git clone https://github.com/revbayes/revbayes.git /revbayes-build
    cd /revbayes-build
    git checkout {{ version }}

%environment
    export PATH=$PATH:/scif/apps/rb/bin:/scif/apps/rb-mpi/bin

%appinstall rb
    cd /revbayes-build/projects/cmake/
    rm -rf build
    ./build.sh -DCMAKE_INSTALL_PREFIX=${SCIF_APPROOT} -DCMAKE_BUILD_TYPE=Release
    cd build
    make install

%appinstall rbmpi
    apt-get install -y libopenmpi-dev
    cd /revbayes-build/projects/cmake/
    rm -rf build-mpi
    ./build.sh -mpi true -DCMAKE_INSTALL_PREFIX=${SCIF_APPROOT} -DCMAKE_BUILD_TYPE=Release
    cd build-mpi
    make install
